import { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Sparkles, 
  Search, 
  Copy, 
  Check, 
  Download, 
  Lock, 
  Crown, 
  CheckCircle2, 
  Terminal, 
  BookOpen, 
  FileText, 
  Share2, 
  Filter, 
  ExternalLink, 
  ArrowRight,
  Sliders,
  TrendingUp,
  Fingerprint
} from 'lucide-react';
import { toast } from 'sonner';
import { jsPDF } from 'jspdf';
import { ALL_101_PROMPTS, PROMPT_CATEGORIES, GPTPrompt } from '../data/prompts';

interface PromptLibraryProps {
  tier: 'free' | 'pro' | 'enterprise';
  onUpgrade: (selectedTier: 'pro' | 'enterprise') => void;
}

export function PromptLibrary({ tier, onUpgrade }: PromptLibraryProps) {
  const isPro = tier === 'pro' || tier === 'enterprise';
  
  // Search and filter states
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string>('All');
  const [selectedTierFilter, setSelectedTierFilter] = useState<'all' | 'free' | 'pro'>('all');
  
  // Interactive copy state
  const [copiedId, setCopiedId] = useState<string | null>(null);

  // Statistics
  const totalPrompts = ALL_101_PROMPTS.length;
  const freePromptsCount = ALL_101_PROMPTS.filter(p => p.tier === 'free').length;
  const unlockedCount = isPro ? totalPrompts : freePromptsCount;

  // Filtered list
  const filteredPrompts = ALL_101_PROMPTS.filter(prompt => {
    const matchesSearch = 
      prompt.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      prompt.useCase.toLowerCase().includes(searchQuery.toLowerCase()) ||
      prompt.prompt.toLowerCase().includes(searchQuery.toLowerCase()) ||
      prompt.tags.some(tag => tag.toLowerCase().includes(searchQuery.toLowerCase()));

    const matchesCategory = selectedCategory === 'All' || prompt.category === selectedCategory;
    const matchesTier = selectedTierFilter === 'all' || prompt.tier === selectedTierFilter;

    return matchesSearch && matchesCategory && matchesTier;
  });

  const handleCopy = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
    toast.success("Prompt copied to clipboard!", {
      description: "Paste it directly into ChatGPT, Claude, or Gemini for elite business feedback."
    });
  };

  const handleExportMarkdown = (promptObj: GPTPrompt) => {
    try {
      const content = `# AI Product Catalyst Prompt Export
## ${promptObj.title}

- **Category**: ${promptObj.category}
- **Tier**: ${promptObj.tier.toUpperCase()}
- **Tags**: ${promptObj.tags.join(', ')}

### Use Case
${promptObj.useCase}

### Core Prompt Template
\`\`\`text
${promptObj.prompt}
\`\`\`

${promptObj.optionalUpgrade ? `### Optional Upgrade Expansion\n${promptObj.optionalUpgrade}` : ''}

---
*Generated by AI Product Catalyst — Powered by Empire Tool Vault*
`;
      const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `${promptObj.title.toLowerCase().replace(/[^a-z0-9]/g, "-")}-prompt.md`);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      toast.success("Markdown Prompt exported successfully!");
    } catch (e) {
      console.error(e);
      toast.error("Markdown export failed.");
    }
  };

  const handleExportPDF = (promptObj: GPTPrompt) => {
    try {
      const doc = new jsPDF();
      
      // Header Branding
      doc.setFont("helvetica", "bold");
      doc.setFontSize(22);
      doc.setTextColor(29, 78, 216); // blue-700
      doc.text("AI PRODUCT CATALYST", 14, 20);
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);
      doc.text("Powered by Empire Tool Vault | Secure Strategy Repository", 14, 26);
      
      doc.setDrawColor(220, 220, 225);
      doc.line(14, 30, 196, 30);
      
      // Prompt Details
      doc.setFontSize(15);
      doc.setTextColor(17, 24, 39); // gray-900
      doc.setFont("helvetica", "bold");
      doc.text(promptObj.title, 14, 40);
      
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(75, 85, 99); // gray-600
      doc.text(`Category: ${promptObj.category}`, 14, 47);
      doc.text(`Access Level: ${promptObj.tier === 'free' ? 'Starter (Free)' : 'Premium (Pro)'}`, 14, 53);
      doc.text(`Tags: ${promptObj.tags.join(', ')}`, 14, 59);
      
      doc.setDrawColor(240, 240, 245);
      doc.line(14, 65, 196, 65);
      
      // Use Case
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(17, 24, 39);
      doc.text("Strategic Use Case:", 14, 73);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(55, 65, 81);
      const useCaseLines = doc.splitTextToSize(promptObj.useCase, 182);
      doc.text(useCaseLines, 14, 79);
      
      let yPos = 81 + (useCaseLines.length * 5.5);
      
      // Core Prompt
      doc.setFont("helvetica", "bold");
      doc.setTextColor(17, 24, 39);
      doc.text("Core Prompt Template:", 14, yPos);
      
      doc.setFont("courier", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(31, 41, 55);
      
      const promptLines = doc.splitTextToSize(promptObj.prompt, 182);
      doc.text(promptLines, 14, yPos + 6);
      
      yPos = yPos + 6 + (promptLines.length * 4.8);
      
      // Optional Upgrade
      if (promptObj.optionalUpgrade) {
        if (yPos > 240) {
          doc.addPage();
          yPos = 20;
        }
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.setTextColor(17, 24, 39);
        doc.text("Optional Premium Expansion Framework:", 14, yPos + 6);
        
        doc.setFont("helvetica", "normal");
        doc.setTextColor(55, 65, 81);
        const upgradeLines = doc.splitTextToSize(promptObj.optionalUpgrade, 182);
        doc.text(upgradeLines, 14, yPos + 12);
      }
      
      const safeTitle = promptObj.title.toLowerCase().replace(/[^a-z0-9]/g, "-");
      doc.save(`${safeTitle}-prompt.pdf`);
      toast.success("PDF Prompt exported successfully!");
    } catch (err) {
      console.error("PDF generation failed:", err);
      toast.error("Failed to generate PDF. Falling back to Markdown export.");
      handleExportMarkdown(promptObj);
    }
  };

  return (
    <div className="space-y-10">
      {/* Dynamic Vault Dashboard Header */}
      <div className="relative bg-gradient-to-br from-gray-900 to-black text-white rounded-3xl p-8 overflow-hidden shadow-2xl border border-gray-800">
        <div className="absolute top-0 right-0 w-96 h-96 bg-gradient-to-br from-blue-500/20 via-purple-500/10 to-transparent rounded-full blur-3xl pointer-events-none" />
        
        <div className="relative z-10 flex flex-col lg:flex-row lg:items-center justify-between gap-8">
          <div className="space-y-4 max-w-2xl">
            <div className="inline-flex items-center gap-2 px-3 py-1 bg-blue-500/10 border border-blue-500/20 text-blue-400 rounded-xl text-xs font-black tracking-widest uppercase">
              <Sparkles className="w-3.5 h-3.5 text-blue-400" />
              <span>Vault Exclusive</span>
            </div>
            
            <h1 className="text-4xl font-extrabold tracking-tight sm:text-5xl">
              101 GPT Prompts <br/>
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 via-indigo-400 to-purple-400">
                To Run Your Business
              </span>
            </h1>
            
            <p className="text-gray-400 text-sm sm:text-base leading-relaxed">
              Unlock a comprehensive collection of elite, engineered prompts mapped to every stage of business execution. Formulate premium offers, optimize pricing tiers, automate tasks, and solve founder blockages immediately.
            </p>
          </div>

          {/* Stats Ring Card */}
          <div className="bg-white/5 border border-white/10 backdrop-blur-md rounded-2xl p-6 flex flex-col items-center justify-center text-center w-full lg:w-64 flex-shrink-0 relative overflow-hidden">
            <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-blue-500 to-indigo-500" />
            <span className="text-xs font-black text-gray-400 uppercase tracking-widest mb-1">
              Vault Unlocked Progress
            </span>
            <div className="text-5xl font-black font-mono tracking-tighter text-white mt-1">
              {unlockedCount} <span className="text-gray-600">/</span> {totalPrompts}
            </div>
            
            {/* Progress Bar */}
            <div className="w-full bg-gray-800 h-2 rounded-full mt-4 overflow-hidden">
              <div 
                className="bg-gradient-to-r from-blue-500 to-indigo-500 h-full rounded-full transition-all duration-1000"
                style={{ width: `${(unlockedCount / totalPrompts) * 100}%` }}
              />
            </div>

            {!isPro ? (
              <button 
                onClick={() => onUpgrade('pro')}
                className="mt-4 w-full py-2 bg-gradient-to-r from-yellow-500 to-amber-600 hover:from-yellow-600 hover:to-amber-700 text-black font-black text-xs rounded-xl shadow-lg shadow-yellow-500/10 transition-all flex items-center justify-center gap-1.5 cursor-pointer"
              >
                <Crown className="w-3.5 h-3.5 fill-black" />
                <span>Unlock All 101 Prompts</span>
              </button>
            ) : (
              <div className="mt-4 flex items-center gap-1.5 text-emerald-400 text-xs font-black uppercase tracking-wider">
                <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                <span>VIP Pro Access Active</span>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Filter and Search Panel */}
      <div className="bg-white/50 dark:bg-gray-900/40 backdrop-blur-xl border border-gray-200/50 dark:border-gray-800/50 rounded-3xl p-6 space-y-6">
        <div className="flex flex-col lg:flex-row gap-4 items-center justify-between">
          
          {/* Search Box */}
          <div className="relative w-full lg:max-w-md">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 dark:text-gray-500" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search by title, keyword, tags, or use-case..."
              className="w-full pl-11 pr-4 py-3 bg-gray-50/50 dark:bg-gray-950/40 border border-gray-200 dark:border-gray-800 rounded-2xl text-sm focus:outline-none focus:border-blue-500 dark:focus:border-blue-400 transition-all"
            />
          </div>

          {/* Quick Filters */}
          <div className="flex flex-wrap items-center gap-3 w-full lg:w-auto justify-end">
            <div className="inline-flex bg-gray-150/50 dark:bg-gray-950/40 p-1.5 rounded-2xl border border-gray-200 dark:border-gray-800">
              <button 
                onClick={() => setSelectedTierFilter('all')}
                className={`px-4 py-2 text-xs font-black rounded-xl transition-all cursor-pointer ${selectedTierFilter === 'all' ? 'bg-white dark:bg-gray-800 text-gray-900 dark:text-white shadow-sm' : 'text-gray-500 hover:text-gray-900 dark:hover:text-gray-300'}`}
              >
                All Prompts
              </button>
              <button 
                onClick={() => setSelectedTierFilter('free')}
                className={`px-4 py-2 text-xs font-black rounded-xl transition-all cursor-pointer ${selectedTierFilter === 'free' ? 'bg-white dark:bg-gray-800 text-gray-900 dark:text-white shadow-sm' : 'text-gray-500 hover:text-gray-900 dark:hover:text-gray-300'}`}
              >
                Starter (Free)
              </button>
              <button 
                onClick={() => setSelectedTierFilter('pro')}
                className={`px-4 py-2 text-xs font-black rounded-xl transition-all cursor-pointer ${selectedTierFilter === 'pro' ? 'bg-white dark:bg-gray-800 text-gray-900 dark:text-white shadow-sm' : 'text-gray-500 hover:text-gray-900 dark:hover:text-gray-300'}`}
              >
                Pro Gated ({totalPrompts - freePromptsCount})
              </button>
            </div>
          </div>
        </div>

        {/* Category Scroll Tabs */}
        <div className="space-y-2">
          <label className="text-[10px] font-black uppercase text-gray-400 dark:text-gray-500 tracking-widest flex items-center gap-1.5">
            <Filter className="w-3.5 h-3.5" />
            <span>Filter by GTM Business Category</span>
          </label>
          <div className="flex flex-wrap gap-2 overflow-x-auto pb-2 scrollbar-hide">
            <button
              onClick={() => setSelectedCategory('All')}
              className={`px-4 py-2 rounded-xl text-xs font-bold transition-all cursor-pointer whitespace-nowrap border ${
                selectedCategory === 'All'
                  ? 'bg-blue-600 border-blue-600 text-white shadow-md shadow-blue-500/10'
                  : 'bg-white dark:bg-gray-950 border-gray-200 dark:border-gray-800 text-gray-600 dark:text-gray-400 hover:border-gray-300 dark:hover:border-gray-700'
              }`}
            >
              All Categories ({totalPrompts})
            </button>
            {PROMPT_CATEGORIES.map((cat) => {
              const count = ALL_101_PROMPTS.filter(p => p.category === cat).length;
              return (
                <button
                  key={cat}
                  onClick={() => setSelectedCategory(cat)}
                  className={`px-4 py-2 rounded-xl text-xs font-bold transition-all cursor-pointer whitespace-nowrap border ${
                    selectedCategory === cat
                      ? 'bg-blue-600 border-blue-600 text-white shadow-md shadow-blue-500/10'
                      : 'bg-white dark:bg-gray-950 border-gray-200 dark:border-gray-800 text-gray-600 dark:text-gray-400 hover:border-gray-300 dark:hover:border-gray-700'
                  }`}
                >
                  {cat} ({count})
                </button>
              );
            })}
          </div>
        </div>
      </div>

      {/* Prompts Layout Grid */}
      <div className="grid grid-cols-1 gap-8">
        <AnimatePresence mode="popLayout">
          {filteredPrompts.map((prompt, index) => {
            const isGated = !isPro && prompt.tier === 'pro';
            
            return (
              <motion.div
                key={prompt.id}
                layout
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.95 }}
                transition={{ duration: 0.3 }}
                className={`group bg-white dark:bg-gray-900 border ${
                  isGated 
                    ? 'border-amber-500/25 dark:border-amber-500/15 bg-amber-500/[0.01]' 
                    : 'border-gray-200 dark:border-gray-800 hover:border-blue-500/40 dark:hover:border-blue-400/30'
                } rounded-3xl overflow-hidden shadow-lg hover:shadow-xl transition-all relative`}
              >
                {/* Header Section */}
                <div className="p-6 border-b border-gray-100 dark:border-gray-800/80 bg-gray-50/50 dark:bg-gray-900/50 flex flex-col md:flex-row md:items-center justify-between gap-4">
                  <div className="space-y-2">
                    <div className="flex items-center gap-2.5">
                      <Terminal className="w-5 h-5 text-blue-600 dark:text-blue-400" />
                      <h3 className="text-lg font-bold text-gray-900 dark:text-white leading-tight">
                        {prompt.title}
                      </h3>
                      {prompt.tier === 'free' ? (
                        <span className="px-2 py-0.5 bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 text-[10px] font-black rounded-lg uppercase tracking-wider select-none">
                          Starter
                        </span>
                      ) : (
                        <span className="px-2.5 py-0.5 bg-yellow-100 dark:bg-yellow-950/40 text-yellow-700 dark:text-yellow-400 border border-yellow-500/10 text-[10px] font-black rounded-lg uppercase tracking-wider inline-flex items-center gap-1 select-none">
                          <Crown className="w-3 h-3 fill-yellow-500" />
                          <span>PRO</span>
                        </span>
                      )}
                    </div>
                    <p className="text-xs text-gray-500 dark:text-gray-400">
                      {prompt.category} • <span className="font-semibold italic text-gray-600 dark:text-gray-300">Use Case: {prompt.useCase}</span>
                    </p>
                    
                    {/* Tags */}
                    <div className="flex flex-wrap gap-1.5 pt-1">
                      {prompt.tags.map((tag, tIndex) => (
                        <span key={tIndex} className="px-2 py-0.5 bg-gray-100 dark:bg-gray-800/50 text-gray-600 dark:text-gray-400 text-[10px] font-semibold rounded-md">
                          #{tag}
                        </span>
                      ))}
                    </div>
                  </div>

                  {/* Actions (Only active if unlocked) */}
                  {!isGated && (
                    <div className="flex items-center gap-2 self-end md:self-auto flex-shrink-0">
                      
                      {/* Copy */}
                      <button
                        onClick={() => handleCopy(prompt.prompt, prompt.id)}
                        className="p-2.5 bg-white dark:bg-gray-800 hover:bg-gray-100 dark:hover:bg-gray-700 text-gray-700 dark:text-gray-300 border border-gray-200 dark:border-gray-700 rounded-xl transition-all hover:scale-105 cursor-pointer flex items-center justify-center gap-1.5 text-xs font-bold"
                        title="Copy prompt template"
                      >
                        {copiedId === prompt.id ? (
                          <>
                            <Check className="w-4 h-4 text-green-500 animate-pulse" />
                            <span className="text-green-500">Copied!</span>
                          </>
                        ) : (
                          <>
                            <Copy className="w-4 h-4 text-gray-400" />
                            <span>Copy</span>
                          </>
                        )}
                      </button>

                      {/* Export Dropdown / Buttons */}
                      <button
                        onClick={() => handleExportMarkdown(prompt)}
                        className="p-2.5 bg-white dark:bg-gray-800 hover:bg-gray-100 dark:hover:bg-gray-700 text-gray-700 dark:text-gray-300 border border-gray-200 dark:border-gray-700 rounded-xl transition-all hover:scale-105 cursor-pointer flex items-center justify-center gap-1.5 text-xs font-bold"
                        title="Export Markdown file"
                      >
                        <Download className="w-4 h-4 text-gray-400" />
                        <span>MD</span>
                      </button>

                      <button
                        onClick={() => handleExportPDF(prompt)}
                        className="p-2.5 bg-white dark:bg-gray-800 hover:bg-gray-100 dark:hover:bg-gray-700 text-gray-700 dark:text-gray-300 border border-gray-200 dark:border-gray-700 rounded-xl transition-all hover:scale-105 cursor-pointer flex items-center justify-center gap-1.5 text-xs font-bold"
                        title="Export PDF Document"
                      >
                        <FileText className="w-4 h-4 text-gray-400" />
                        <span>PDF</span>
                      </button>
                    </div>
                  )}
                </div>

                {/* Body Content (Blurred if Gated) */}
                <div className="relative">
                  {isGated ? (
                    <div className="p-6 bg-gray-950 select-none pointer-events-none relative h-48 overflow-hidden">
                      {/* Heavy blur layout of prompt template */}
                      <pre className="text-xs text-green-500/20 font-mono blur-[6px] whitespace-pre-wrap leading-relaxed select-none">
                        Goal: Create an automated workflow that connects [CRM_NAME] with your database.
                        Trigger: A payment completion transaction of $[VALUE] occurs in Stripe.
                        Filtering & Logic: Check if they are a returning customer using security logs...
                        Actions: Generate custom onboarding credentials, create Google Doc templates...
                        Optional Upgrades: Export logs to a dedicated Slack channel.
                      </pre>
                      
                      {/* Premium Overlay Mask */}
                      <div className="absolute inset-0 bg-gradient-to-t from-black via-black/95 to-black/85 flex flex-col items-center justify-center p-6 text-center pointer-events-auto">
                        <div className="w-12 h-12 rounded-2xl bg-amber-500/10 border border-amber-500/20 flex items-center justify-center mb-3">
                          <Lock className="w-5 h-5 text-amber-500" />
                        </div>
                        <h4 className="font-extrabold text-sm text-white flex items-center gap-1.5">
                          Premium Vault Prompt #{index + 1}
                        </h4>
                        <p className="text-[11px] text-gray-400 mt-1 max-w-sm">
                          This structured prompt template is gated under the Pro Membership. Get access to all 101 GPT prompts to run your business today.
                        </p>
                        
                        <button
                          onClick={() => onUpgrade('pro')}
                          className="mt-4 px-4 py-2 bg-gradient-to-r from-yellow-500 to-amber-600 hover:from-yellow-600 hover:to-amber-700 text-black font-black text-xs rounded-xl shadow-lg shadow-yellow-500/10 transition-all flex items-center gap-1.5 cursor-pointer"
                        >
                          <Crown className="w-3.5 h-3.5 fill-black" />
                          <span>Unlock Pro Prompt Library</span>
                        </button>
                      </div>
                    </div>
                  ) : (
                    <div className="p-0">
                      <div className="p-6 bg-gray-950 dark:bg-black/80 font-mono text-sm leading-relaxed overflow-x-auto relative">
                        <div className="absolute top-3 right-3 text-[9px] font-bold text-green-500/40 uppercase tracking-widest pointer-events-none select-none">
                          Prompt Template Area
                        </div>
                        <pre className="text-xs text-green-400 whitespace-pre-wrap break-words leading-relaxed select-text font-mono">
                          {prompt.prompt}
                        </pre>
                      </div>
                      
                      {/* Optional Upgrade Section if Unlocked */}
                      {prompt.optionalUpgrade && (
                        <div className="p-6 bg-blue-50/30 dark:bg-blue-950/10 border-t border-gray-100 dark:border-gray-800/80">
                          <h4 className="text-xs font-bold text-blue-700 dark:text-blue-400 flex items-center gap-1.5 uppercase tracking-wider mb-2 select-none">
                            <Sparkles className="w-3.5 h-3.5" />
                            <span>Optional Premium Upgrade Prompt Extension</span>
                          </h4>
                          <p className="text-xs text-gray-600 dark:text-gray-300 leading-relaxed font-sans italic">
                            "{prompt.optionalUpgrade}"
                          </p>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              </motion.div>
            );
          })}
        </AnimatePresence>
      </div>

      {/* Empty Search State */}
      {filteredPrompts.length === 0 && (
        <motion.div 
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="text-center py-16 bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-3xl"
        >
          <BookOpen className="w-12 h-12 text-gray-400 mx-auto mb-4" />
          <h3 className="font-bold text-gray-900 dark:text-white text-base">No Matching Prompts Found</h3>
          <p className="text-xs text-gray-500 mt-1 max-w-sm mx-auto">
            Try adjusting your search terms or selecting a different GTM business category filter above.
          </p>
        </motion.div>
      )}

      {/* Inside-Library Powered by Empire Tool Vault Branding */}
      <div className="pt-4 border-t border-gray-200/40 dark:border-gray-800/40 flex items-center justify-center gap-1.5 text-xs text-gray-400 dark:text-gray-500 font-mono select-none">
        <span>Vault verified by</span>
        <span className="font-bold text-blue-600 dark:text-blue-400 flex items-center gap-1">
          <Fingerprint className="w-3.5 h-3.5" />
          Empire Tool Vault
        </span>
      </div>
    </div>
  );
}
